type DropdownOption = {
  value: string;
  text: string;
};

export const dropdownOptions: DropdownOption[] = [
  { value: '""', text: "category" },
  { value: "cs.AI", text: "cs.AI" },
  { value: "cs.AR", text: "cs.AR" },
  { value: "cs.CC", text: "cs.CC" },
  { value: "cs.CE", text: "cs.CE" },
  { value: "cs.CG", text: "cs.CG" },
  { value: "cs.CL", text: "cs.CL" },
  { value: "cs.CR", text: "cs.CR" },
  { value: "cs.CV", text: "cs.CV" },
  { value: "cs.CY", text: "cs.CY" },
  { value: "cs.DB", text: "cs.DB" },
  { value: "cs.DC", text: "cs.DC" },
  { value: "cs.DL", text: "cs.DL" },
  { value: "cs.DM", text: "cs.DM" },
  { value: "cs.DS", text: "cs.DS" },
  { value: "cs.ET", text: "cs.ET" },
  { value: "cs.FL", text: "cs.FL" },
  { value: "cs.GL", text: "cs.GL" },
  { value: "cs.GR", text: "cs.GR" },
  { value: "cs.GT", text: "cs.GT" },
  { value: "cs.HC", text: "cs.HC" },
  { value: "cs.IR", text: "cs.IR" },
  { value: "cs.IT", text: "cs.IT" },
  { value: "cs.LG", text: "cs.LG" },
  { value: "cs.LO", text: "cs.LO" },
  { value: "cs.MA", text: "cs.MA" },
  { value: "cs.MM", text: "cs.MM" },
  { value: "cs.MS", text: "cs.MS" },
  { value: "cs.NA", text: "cs.NA" },
  { value: "cs.NE", text: "cs.NE" },
  { value: "cs.NI", text: "cs.NI" },
  { value: "cs.OH", text: "cs.OH" },
  { value: "cs.OS", text: "cs.OS" },
  { value: "cs.PF", text: "cs.PF" },
  { value: "cs.PL", text: "cs.PL" },
  { value: "cs.RO", text: "cs.RO" },
  { value: "cs.SC", text: "cs.SC" },
  { value: "cs.SD", text: "cs.SD" },
  { value: "cs.SE", text: "cs.SE" },
  { value: "cs.SI", text: "cs.SI" },
  { value: "cs.SY", text: "cs.SY" },
];
