import axios from "axios";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { euiPaletteColorBlind } from "@elastic/eui";
import Group, { FacetGroupProps } from "@/components/Facets/Group";
import { flattenFacets } from "@/utils/facets";

export default function Home() {
  const [facetFields, setFacetFields] = useState<{
    [key: string]: (string | number)[];
  } | null>(null);

  const FACETS: FacetGroupProps[] = [
    {
      title: "Authors",
      color: euiPaletteColorBlind()[0],
      facets: flattenFacets(facetFields?.authors || []),
    },
    {
      title: "Versions",
      color: euiPaletteColorBlind()[1],
      facets: flattenFacets(facetFields?.["versions.version"] || []),
    },
  ];

  useEffect(() => {
    axios
      .get(
        `http://localhost:8983/solr/abstracts/select?facet.contains.ignoreCase=false&facet=true&facet.field=versions.version&facet.field=authors&facet.limit=20&facet.missing=false&facet.sort=count&facet=true&indent=true&q.op=OR&q=title%3Aautomata&useParams=`
      )
      .then((response) => {
        setFacetFields(response.data.facet_counts.facet_fields);
      });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {FACETS.map((facet) => (
        <Group
          key={facet.title}
          title={facet.title}
          color={facet.color}
          facets={facet.facets}
        />
      ))}
    </>
  );
}
